[buildPlans.IIosevka]
family = "I.Iosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IIosevka.variants.design]
one = "base"
two = "curly-neck"
four = "closed"
five = "oblique-arched"
seven = "curly-serifless"

[buildPlans.IIosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IIosevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IIosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"